spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
books.names=Annihilation of Caste,Castes in India: Their Mechanism, Genesis and Development,The Untouchables: Who are They and Why They Became Untouchables,The Buddha and His Dhamma,Waiting for a Visa